@TOKEN=

GET http://127.0.0.1:8000/evaluations/tilen/chart-a
Authorization: Bearer {{TOKEN}}

### Ask question
POST http://127.0.0.1:14900/evaluations/tilen/chart-b
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "question":"what does purple color represen"
}